version: 2.1

orbs:
    wpengine: ryanshoover/wpengine@dev:alpha

workflows:
    version: 2

    test-deploy:
        jobs:
            - wpengine/lint:
                context: DXT
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /^\d+\.\d+\.\d+$/
            - wpengine/codeception:
                context: DXT
                package_name: test-plugin-orb-wpengine=deploy
                package_type: plugin
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /^\d+\.\d+\.\d+$/
            - wpengine/deploy_fury:
                context: DXT
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^\d+\.\d+\.\d+$/
                requires:
                    - wpengine/lint
                    - wpengine/codeception
